### ISSUE TITLE
Point Cache Animation 

### ISSUE THREAD

**Issue by tonjimenez** [Unity-Technologies/VFXToolbox#13]
I have a point cloud that follows my alembic animation. I was trying to export the point cloud with animation but it looks like it only exports out the first frame or the current frame the timeline is on. Does the Houdini pCache exporter have support for animation?

**Comment by peeweek** [comment]
Hello, pCache animation in a single file is not supported at the moment but is planned for a future point cache update.

Right now, what you can do is to export one pCache file per frame using houdini wildcards in the file name (for instance `$HIP/MyPointCache_$F3.pcache`  (regarding wildcards `$F` means frame number and `$F3` add leading zeroes in order to have 3-digits, for instance 001, 013, 134).

**Comment by sambeebe** [comment]
Exporting multiple pCache is fine, does anyone know how to actually loop through multiple pcaches in Unity?

**Comment by Conflagz** [comment]
Does anyone have a good process for looping through each frame yet?

**Comment by SilenSang** [comment]
> Hello, pCache animation in a single file is not supported at the moment but is planned for a future point cache update.
> 
> Right now, what you can do is to export one pCache file per frame using houdini wildcards in the file name (for instance `$HIP/MyPointCache_$F3.pcache` (regarding wildcards `$F` means frame number and `$F3` add leading zeroes in order to have 3-digits, for instance 001, 013, 134).

Hope for this update.
